// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250810135652_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "apple1",
                            Price = 5000m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "apple2",
                            Price = 3000m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "apple3",
                            Price = 2000m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "apple4",
                            Price = 4000m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "apple5",
                            Price = 17000m,
                            Stock = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
