// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250814080449_AddCategoryTable")]
    partial class AddCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("dotnet_store.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Elektronik ürünler",
                            IsActive = true,
                            Name = "Elektronik",
                            Url = "elektronik"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Giyim ürünleri",
                            IsActive = true,
                            Name = "Giyim",
                            Url = "giyim"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ev ve yaşam ürünleri",
                            IsActive = true,
                            Name = "Ev & Yaşam",
                            Url = "ev-yasam"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HomePage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "lorem ipsum",
                            HomePage = true,
                            Image = "1.jpeg",
                            IsActive = true,
                            Name = "apple1",
                            Price = 5000m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "lorem ipsum",
                            HomePage = false,
                            Image = "2.jpeg",
                            IsActive = true,
                            Name = "apple2",
                            Price = 3000m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "lorem ipsum",
                            HomePage = true,
                            Image = "3.jpeg",
                            IsActive = true,
                            Name = "apple3",
                            Price = 2000m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "lorem ipsum",
                            HomePage = true,
                            Image = "4.jpeg",
                            IsActive = true,
                            Name = "apple4",
                            Price = 4000m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "lorem ipsum",
                            HomePage = false,
                            Image = "5.jpeg",
                            IsActive = true,
                            Name = "apple5",
                            Price = 17000m,
                            Stock = 0
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.HasOne("dotnet_store.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("dotnet_store.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
